# Generated by Django 3.0.8 on 2021-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=200)),
                ('aboutyourself', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('fieldofinterest', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
                ('permanentaddress', models.CharField(max_length=2000)),
                ('presentaddress', models.CharField(max_length=2000)),
                ('cv', models.FileField(upload_to='file/')),
            ],
        ),
    ]
