# Generated by Django 3.0.8 on 2021-04-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv',
        ),
    ]
