# Generated by Django 3.0.8 on 2021-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_userprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pastjobdesignation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='presentjobdesignation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
