# Generated by Django 3.0.8 on 2021-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210423_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pastjobdesignation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='presentjobdesignation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
