# Generated by Django 3.0.8 on 2021-05-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210512_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pastjobdesignation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='presentjobdesignation',
            field=models.CharField(max_length=100),
        ),
    ]
