# Generated by Django 3.0.8 on 2021-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210512_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pastjobdesignation',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='presentjobdesignation',
            field=models.CharField(max_length=2000),
        ),
    ]
